project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd"
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.qmd"
        - text: "Hands-on Exercise 3 Part 2"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03Part2.qmd"
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.qmd"
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04Chpt10.qmd"  
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.qmd" 
        - text: "Hands-on Exercise 6"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.qmd" 
        - text: "Hands-on Exercise 7"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.qmd" 
        - text: "Hands-on Exercise 8"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.qmd" 
    - text: "In Class Exercise"
      menu:
        - text: "In Class Exercise 1"
          href: "InClassEx/In-class_Ex01/In-class_Ex01.qmd"
        - text: "In Class Exercise 3"
          href: "InClassEx/In-class_Ex03/In-class_Ex03.qmd"
        - text: "In Class Exercise 4"
          href: "InClassEx/In-class_Ex04/In-class_Ex04.qmd"
        - text: "In Class Exercise 5"
          href: "InClassEx/In-class_Ex05/In-class_Ex05.qmd"
        - text: "In Class Exercise 7"
          href: "InClassEx/In-class_Ex07/In-class_Ex07.qmd"
    - text: "Take Home Exercise"
      menu:
        - text: "Take Home Exercise 1"
          href: "TakeHomeEx/TakeHomeEx1/TakehomeExercise1.html"
        - text: "Take Home Exercise 2"
          href: "TakeHomeEx/TakeHomeEx2/TakehomeEx2.html"
        - text: "Take Home Exercise 3"
          href: "TakeHomeEx/TakeHomeEx3/TakehomeEx03.html"
        
    right:    
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: Minty
    css: styles.css
    toc: true
    
executive:
  echo: true #if you want to display the code chunk, true is yes display code chunk
  eval: true
  warning: false  #this will make warning not appear
editor: visual

